### ISSUE TITLE
UnsupportedAudioFileException thrown even though file is .wav

### ISSUE THREAD

**Issue by abomin0** [kikugie/voicechat-soundboard#11]
as the title says, the mod desc says explicitly to use .wav format files, and .wav format files throw an unsupported file error.
error:`javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
at dev.kikugie.soundboard.util.AudioUtilKt.convert(AudioUtil.kt:30)
at dev.kikugie.soundboard.entrypoint.SoundboardEntrypoint$DefaultImpls.scheduleStream(SoundboardEntrypoint.kt:46)
at dev.kikugie.soundboard.entrypoint.SVCEntrypoint.scheduleStream(SVCEntrypoint.kt:18)
at dev.kikugie.soundboard.entrypoint.SoundboardEntrypoint$DefaultImpls.scheduleStream$default(SoundboardEntrypoint.kt:41)
at dev.kikugie.soundboard.entrypoint.SoundboardAccess.play(SoundboardAccess.kt:17)
at dev.kikugie.soundboard.gui.screen.SoundBrowser.create$lambda$17$lambda$16$lambda$15$lambda$14(SoundBrowser.kt:148)
at io.wispforest.owo.ui.component.ButtonComponent.lambda$onPress$1(ButtonComponent.java:59)
at net.minecraft.class_4185.method_25306(class_4185.java:96)
at net.minecraft.class_4264.method_25348(class_4264.java:48)
at net.minecraft.class_339.method_25402(class_339.java:141)
at io.wispforest.owo.ui.component.VanillaWidgetComponent.onMouseDown(VanillaWidgetComponent.java:151)
at net.minecraft.class_339.onMouseDown(class_339.java:1151)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.container.CollapsibleContainer.onMouseDown(CollapsibleContainer.java:120)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.container.ScrollContainer.onMouseDown(ScrollContainer.java:205)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170)
at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212)
at io.wispforest.owo.ui.core.OwoUIAdapter.method_25402(OwoUIAdapter.java:218)
at net.minecraft.class_4069.method_25402(class_4069.java:38)
at net.minecraft.class_312.method_1611(class_312.java:107)
at net.minecraft.class_437.method_25412(class_437.java:431)
at net.minecraft.class_312.method_1601(class_312.java:107)
at net.minecraft.class_312.method_22686(class_312.java:196)
at net.minecraft.class_1255.execute(class_1255.java:108)
at net.minecraft.class_312.method_22684(class_312.java:196)
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
`

**Comment by kikugie** [comment]
Can you send the file that's causing this?
